name: Build luci-app-button

on:
workflow_dispatch:
inputs:
tag:
description: "Release Tag"
required: false
default: ""

permissions:
contents: write

jobs:
build:
strategy:
fail-fast: false
matrix:
sdk:
- 24.10.6
- SNAPSHOT


runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v4

  - name: Build Package
    uses: openwrt/gh-action-sdk@main
    env:
      ARCH: aarch64_cortex-a53-${{ matrix.sdk }}
      FEEDNAME: button_ci
      PACKAGES: luci-app-button
      NO_REFRESH_CHECK: 1
      NO_SHFMT_CHECK: 1
      V: s

  - name: Upload Artifacts
    uses: actions/upload-artifact@v4
    with:
      name: ${{ matrix.sdk }}
      path: |
        bin/packages/**/*.ipk
        bin/packages/**/*.apk


release:
needs: build
if: github.event.inputs.tag != ''
runs-on: ubuntu-latest


steps:
  - uses: actions/download-artifact@v4
    with:
      path: artifacts

  - run: |
      mkdir release
      find artifacts -name "*.ipk" -exec cp {} release/ \;
      find artifacts -name "*.apk" -exec cp {} release/ \;

  - uses: softprops/action-gh-release@v2
    with:
      tag_name: ${{ github.event.inputs.tag }}
      files: release/*

